name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:
    
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile 
