name: Build and Publish Docker Image to DockerHub

on:
  push:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          push: true
          pull: true
          tags: dxatscale/sfpowerscripts:latest
          cache-from: type=registry,ref=dxatscale/sfpowerscripts:buildcache
          cache-to: type=registry,ref=dxatscale/sfpowerscripts:buildcache,mode=max
      
